"""
Type stubs for the subset of Z3 we use in this project.

Z3's own type stubs are either missing or overly broad (e.g., If() is typed
to return Tactic | Probe | ExprRef). These stubs give correct, narrow types
for the functions we actually call, so type checkers like pyright/mypy produce
useful results instead of false positives.

Usage: place this file alongside your Z3 scripts. Your type checker should
pick it up automatically when you import from z3. If it doesn't, you may
need to configure your type checker's stub search path.

Note: this only covers what z3_cegis_demo.py uses. Extend as needed.
"""

from typing import Optional, overload

# --- Base types (mirrors z3.z3 class hierarchy) ---

class Z3PPObject: ...

class AstRef(Z3PPObject): ...

class ExprRef(AstRef):
    def __eq__(self, other: object) -> BoolRef: ...  # type: ignore[override]
    def __ne__(self, other: object) -> BoolRef: ...  # type: ignore[override]

class ArithRef(ExprRef):
    def __add__(self, other: ArithRef | int) -> ArithRef: ...
    def __radd__(self, other: int) -> ArithRef: ...
    def __sub__(self, other: ArithRef | int) -> ArithRef: ...
    def __rsub__(self, other: int) -> ArithRef: ...
    def __mul__(self, other: ArithRef | int) -> ArithRef: ...
    def __rmul__(self, other: int) -> ArithRef: ...
    def __truediv__(self, other: ArithRef | int) -> ArithRef: ...
    def __mod__(self, other: ArithRef | int) -> ArithRef: ...
    def __neg__(self) -> ArithRef: ...
    def __ge__(self, other: ArithRef | int) -> BoolRef: ...
    def __gt__(self, other: ArithRef | int) -> BoolRef: ...
    def __le__(self, other: ArithRef | int) -> BoolRef: ...
    def __lt__(self, other: ArithRef | int) -> BoolRef: ...

class BoolRef(ExprRef): ...

class IntNumRef(ArithRef):
    def as_long(self) -> int: ...

class ModelRef:
    def evaluate(self, expr: ExprRef) -> ExprRef: ...

class CheckSatResult: ...

# --- Solver ---

class Solver:
    def add(self, *args: BoolRef | list[BoolRef]) -> None: ...
    def check(self) -> CheckSatResult: ...
    def model(self) -> ModelRef: ...
    def reset(self) -> None: ...

# --- Constructors ---

def Int(name: str, ctx: Optional[object] = None) -> ArithRef: ...
def IntVal(val: int, ctx: Optional[object] = None) -> IntNumRef: ...

# --- The key fix: If() returns the same type as its branches ---

@overload
def If(a: BoolRef, b: ArithRef, c: ArithRef, ctx: Optional[object] = None) -> ArithRef: ...
@overload
def If(a: BoolRef, b: ArithRef, c: int, ctx: Optional[object] = None) -> ArithRef: ...
@overload
def If(a: BoolRef, b: int, c: ArithRef, ctx: Optional[object] = None) -> ArithRef: ...
@overload
def If(a: BoolRef, b: int, c: int, ctx: Optional[object] = None) -> ArithRef: ...
@overload
def If(a: BoolRef, b: BoolRef, c: BoolRef, ctx: Optional[object] = None) -> BoolRef: ...
@overload
def If(a: BoolRef, b: ExprRef, c: ExprRef, ctx: Optional[object] = None) -> ExprRef: ...
def If(a: object, b: object, c: object, ctx: Optional[object] = None) -> ExprRef: ...

# --- Logical connectives ---

def And(*args: BoolRef | list[BoolRef]) -> BoolRef: ...
def Or(*args: BoolRef | list[BoolRef]) -> BoolRef: ...
def Not(a: BoolRef) -> BoolRef: ...

# --- Constants ---

sat: CheckSatResult
unsat: CheckSatResult
