"""
TN note: this example was generated by Claude Code from a prompt incorporating 
my own problem description. I then went through and did some refinement.

Property-Based Testing Example: Hash Function Avalanche Effect

The "avalanche effect" is a desirable property of cryptographic hash functions:
a small change in input (e.g., flipping one bit or changing one character)
should produce a drastically different output (ideally ~50% of bits change).

This example uses Hypothesis to test whether MD5 exhibits this property.
"""

import hashlib
import random
from hypothesis import given, settings
from hypothesis import strategies as st

def md5_hash(s: str) -> str:
    """Compute the MD5 hash of a string, returning hex digest."""
    return hashlib.md5(s.encode("utf-8")).hexdigest()

def hamming_distance_hex(hex1: str, hex2: str) -> int:
    """
    Compute the Hamming distance (number of differing bits) between two
    hex strings of equal length.
    """
    # Convert hex to integers, XOR them, count the 1-bits
    xor_result = int(hex1, 16) ^ int(hex2, 16)
    return bin(xor_result).count("1")


def mutate_one_char(s: str) -> str:
    """
    Mutate a single character in the string to a different character.
    Returns the mutated string.
    """
    if len(s) == 0:
        return s

    idx = random.randint(0, len(s) - 1)
    original_char = s[idx]

    # Pick a different printable ASCII character
    new_char = original_char
    while new_char == original_char:
        new_char = chr(random.randint(32, 126))  # printable ASCII

    return s[:idx] + new_char + s[idx + 1:]


# MD5 produces 128 bits. Ideal avalanche = ~64 bits differ (50%).
# We'll use a more lenient threshold for demonstration.
MIN_BIT_DISTANCE = 64  # at least 25% of bits should differ

# What happens if we ask for something stronger? Switch to this to see md5 fail.
#MIN_BIT_DISTANCE = 64 # at least 50% of the bits should differ


@given(st.text(min_size=1, max_size=100))
@settings(max_examples=10000)
def test_md5_avalanche_effect(original: str) -> None:
    """
    Property: Changing one character in the input should cause
    a significant change in the MD5 output (many bits differ).
    """
    mutated = mutate_one_char(original)

    # Skip if mutation happened to produce the same string
    # (possible if string has repeated chars)
    if original == mutated:
        return

    hash_original = md5_hash(original)
    hash_mutated = md5_hash(mutated)

    distance = hamming_distance_hex(hash_original, hash_mutated)

    assert distance >= MIN_BIT_DISTANCE, (
        f"Avalanche effect too weak!\n"
        f"  Original: {original!r} -> {hash_original}\n"
        f"  Mutated:  {mutated!r} -> {hash_mutated}\n"
        f"  Hamming distance: {distance} bits (expected >= {MIN_BIT_DISTANCE})"
    )


if __name__ == "__main__":
    # Run the test
    test_md5_avalanche_effect()
    print("All tests passed!")